[theme]
primaryColor = "#eab32a"          # Rowen gold
backgroundColor = "#f8f9fa"       # Light sidebar
secondaryBackgroundColor = "#ffffff"
textColor = "#15325b"             # Rowen navy
font = "sans serif"
